"use client";
import type { Metadata } from 'next'
import { Suspense } from 'react'
import Header from '@/components/Header'
import Footer from '@/components/Footer'
import HomeClient from '@/components/HomeClient'
import { CATEGORY_META } from '@/lib/codes-db'
import { getAllFullCodes } from '@/lib/db/dal'

const BASE = process.env.NEXT_PUBLIC_BASE_URL ?? 'https://autocodefix.com'

export const metadata: Metadata = {
  title: 'AUTO CODE FIX — OBD2 Trouble Code Lookup & Repair Guide',
  description: 'Free OBD2 trouble code lookup. Find causes, symptoms, and step-by-step repair solutions for every check engine light code. 2,600+ codes, AI-powered, free forever.',
  alternates: { canonical: BASE },
  openGraph: {
    title: 'AUTO CODE FIX — OBD2 Trouble Code Lookup & Repair Guide',
    description: 'Free OBD2 trouble code lookup with causes, symptoms, repair costs, and step-by-step fixes.',
    url: BASE,
    type: 'website',
  },
}

// Schema.org JSON-LD for homepage
const websiteSchema = {
  '@context': 'https://schema.org',
  '@type': 'WebSite',
  name: 'AUTO CODE FIX',
  url: BASE,
  description: 'Free OBD2 diagnostic trouble code lookup with AI-powered causes, symptoms, repair guides, and cost estimates for 2,600+ codes.',
  potentialAction: {
    '@type': 'SearchAction',
    target: { '@type': 'EntryPoint', urlTemplate: `${BASE}/?q={search_term_string}` },
    'query-input': 'required name=search_term_string',
  },
}

const faqSchema = {
  '@context': 'https://schema.org',
  '@type': 'FAQPage',
  mainEntity: [
    {
      '@type': 'Question',
      name: 'What is an OBD2 code?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'An OBD2 (On-Board Diagnostics II) code, also called a Diagnostic Trouble Code (DTC), is a standardized alphanumeric code generated by your vehicle\'s computer when it detects a malfunction. Codes start with P (Powertrain), B (Body), C (Chassis), or U (Network) followed by four digits.',
      },
    },
    {
      '@type': 'Question',
      name: 'Can I drive with the check engine light on?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'A steady check engine light usually means you can drive short distances to get it diagnosed. A flashing check engine light means stop driving immediately — it indicates an active misfire that can destroy the catalytic converter within minutes.',
      },
    },
    {
      '@type': 'Question',
      name: 'How much does it cost to fix a check engine light?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'Repair costs vary by code. A loose gas cap (P0442) costs $0–$20. An oxygen sensor (P0131) runs $100–$300. A catalytic converter (P0420) can cost $500–$2,000+. Each code page on AUTO CODE FIX shows a specific estimated cost range.',
      },
    },
    {
      '@type': 'Question',
      name: 'What is AUTO CODE FIX?',
      acceptedAnswer: {
        '@type': 'Answer',
        text: 'AUTO CODE FIX is a free online tool providing instant lookup for 2,600+ OBD2 diagnostic trouble codes. Each code includes plain-language explanations, common causes, symptoms, step-by-step repair guidance, severity ratings, and cost estimates. It also features an AI assistant and supports 12 languages.',
      },
    },
  ],
}

const howToSchema = {
  '@context': 'https://schema.org',
  '@type': 'HowTo',
  name: 'How to Read and Diagnose OBD2 Fault Codes',
  description: 'Step-by-step guide to reading OBD2 diagnostic trouble codes and identifying your check engine light.',
  totalTime: 'PT15M',
  estimatedCost: { '@type': 'MonetaryAmount', currency: 'USD', value: '0', minValue: '0', maxValue: '30' },
  step: [
    { '@type': 'HowToStep', position: 1, name: 'Locate the OBD2 Port', text: 'Find the 16-pin port under the dashboard on the driver\'s side — all cars after 1996 have one.' },
    { '@type': 'HowToStep', position: 2, name: 'Plug In Your Scanner', text: 'Connect an OBD2 scanner or Bluetooth adapter with the ignition off.' },
    { '@type': 'HowToStep', position: 3, name: 'Turn Ignition to ON', text: 'Turn the key to the ON position (engine off) to power the ECU.' },
    { '@type': 'HowToStep', position: 4, name: 'Read the Fault Codes', text: 'Select "Read Codes" — all stored DTCs will be retrieved. Write each one down.' },
    { '@type': 'HowToStep', position: 5, name: 'Look Up Each Code', text: 'Search each code on AUTO CODE FIX for causes, symptoms, and repair steps.' },
    { '@type': 'HowToStep', position: 6, name: 'Diagnose and Repair', text: 'Follow the repair guide from simplest fix to most complex.' },
    { '@type': 'HowToStep', position: 7, name: 'Clear Codes and Verify', text: 'Clear the codes with your scanner and complete a drive cycle to confirm the repair.' },
  ],
}

export default async function HomePage() {
  const codes = await getAllFullCodes()
  return (
    <>
      {/* Schema JSON-LD */}
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(websiteSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(faqSchema) }} />
      <script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(howToSchema) }} />

      <Header />

      {/* Suspense needed for useSearchParams in HomeClient */}
      <Suspense fallback={<div style={{ minHeight: '60vh' }} />}>
        <HomeClient
          codes={codes}
          categoryMeta={CATEGORY_META}
        />
      </Suspense>

      <Footer />
    </>
  )
}
