/**
 * AUTO CODE FIX — Extended Code Database
 * Additional codes to supplement the base database
 */
import { OBDCode } from './codes-db'

export const EXTENDED_CODES: OBDCode[] = [

  /* ═══════════════════ ENGINE (more) ═══════════════════ */
  { code:'P0305', name:'Cylinder 5 Misfire Detected', cat:'engine', sev:'high',
    causes:['Fouled spark plug cylinder 5','Failed ignition coil cylinder 5','Clogged injector cylinder 5','Low compression'],
    symptoms:['Rough idle','Power loss','Check engine light flashing'],
    solutions:['Replace spark plug cylinder 5','Swap and test coil','Test injector','Compression test'],
    diy:true, avg_cost:'$50–$350' },

  { code:'P0306', name:'Cylinder 6 Misfire Detected', cat:'engine', sev:'high',
    causes:['Bad spark plug','Failed ignition coil','Injector fault','Head gasket leak'],
    symptoms:['Rough idle','Engine shake','Power loss'],
    solutions:['Replace spark plug','Replace ignition coil','Test injector','Coolant pressure test'],
    diy:true, avg_cost:'$50–$400' },

  { code:'P0012', name:'Camshaft Position A Timing Over-Retarded Bank 1', cat:'engine', sev:'high',
    causes:['Low oil pressure','Dirty or old engine oil','Faulty OCV (Oil Control Valve)','VVT actuator failure'],
    symptoms:['Rough idle','Hard start','Rattling on startup','Poor fuel economy'],
    solutions:['Change engine oil and filter','Clean or replace OCV','Test VVT solenoid','Check oil pressure'],
    diy:true, avg_cost:'$50–$600', tip:'Always change oil first — dirty oil is the #1 cause of VVT codes.' },

  { code:'P0014', name:'Camshaft Position B Timing Over-Advanced Bank 1', cat:'engine', sev:'high',
    causes:['Faulty exhaust camshaft OCV','Oil sludge in VVT passages','Stretched timing chain','Low oil level'],
    symptoms:['Engine rattle','Rough idle','Stalling','Check engine light'],
    solutions:['Change oil','Clean or replace OCV','Inspect timing chain','Check oil level'],
    diy:true, avg_cost:'$80–$700' },

  { code:'P0017', name:'Crankshaft/Camshaft Correlation Bank 1 Sensor B', cat:'engine', sev:'high',
    causes:['Stretched or jumped timing chain','Faulty cam or crank sensor','Bad VVT solenoid','Worn timing components'],
    symptoms:['Engine runs rough','Hard starting','Rattling noise','Check engine light'],
    solutions:['Inspect timing chain tension','Replace cam/crank sensors','Replace VVT solenoid','Timing chain service'],
    diy:false, avg_cost:'$200–$1500', tip:'A rattling noise with this code strongly suggests timing chain stretch — do not ignore it.' },

  { code:'P0021', name:'Intake Camshaft Position Timing Over-Advanced Bank 2', cat:'engine', sev:'high',
    causes:['Faulty OCV Bank 2','Oil sludge','Stretched timing chain','Low oil pressure'],
    symptoms:['Rough idle','Power loss','Engine noise'],
    solutions:['Oil change','OCV replacement','Timing chain inspection'],
    diy:true, avg_cost:'$80–$700' },

  { code:'P0102', name:'Mass Air Flow (MAF) Sensor Circuit Low Input', cat:'sensors', sev:'med',
    causes:['Dirty or contaminated MAF sensor','Wiring short to ground','Air leak before MAF sensor','Failed MAF sensor'],
    symptoms:['Poor acceleration','Rough idle','High fuel consumption','Black smoke from exhaust'],
    solutions:['Clean MAF sensor with MAF cleaner spray','Inspect wiring harness','Check for air leaks','Replace MAF sensor'],
    diy:true, avg_cost:'$30–$300', tip:'Clean the MAF sensor before replacing it — a $8 can of MAF cleaner fixes this 60% of the time.' },

  { code:'P0103', name:'Mass Air Flow (MAF) Sensor Circuit High Input', cat:'sensors', sev:'med',
    causes:['Wiring short to voltage','Failed MAF sensor','ECM fault','Contaminated sensor element'],
    symptoms:['Rough idle','Poor fuel economy','Hesitation under load'],
    solutions:['Inspect MAF wiring for chafing','Clean MAF sensor','Replace MAF sensor','Check ECM supply voltage'],
    diy:true, avg_cost:'$30–$300' },

  { code:'P0107', name:'MAP Sensor Circuit Low Input', cat:'sensors', sev:'med',
    causes:['Vacuum leak at MAP sensor','Open circuit in signal wire','Failed MAP sensor','Loose sensor connector'],
    symptoms:['Rough idle','Hard starting','Black smoke','Check engine light'],
    solutions:['Inspect MAP sensor vacuum hose','Check sensor connector','Test sensor voltage','Replace MAP sensor'],
    diy:true, avg_cost:'$30–$200' },

  { code:'P0108', name:'MAP Sensor Circuit High Input', cat:'sensors', sev:'med',
    causes:['Short to voltage in signal wire','Failed MAP sensor','Blocked vacuum line','ECM fault'],
    symptoms:['High idle','Lean running','Check engine light'],
    solutions:['Inspect vacuum line for blockage','Check wiring','Replace MAP sensor'],
    diy:true, avg_cost:'$30–$200' },

  { code:'P0113', name:'Intake Air Temperature Sensor Circuit High Input', cat:'sensors', sev:'low',
    causes:['Open circuit in IAT wiring','Faulty IAT sensor','Corroded connector','Failed ECM'],
    symptoms:['Slightly poor fuel economy','Slightly rough cold start','Check engine light'],
    solutions:['Inspect IAT connector','Test IAT resistance','Replace IAT sensor'],
    diy:true, avg_cost:'$20–$150' },

  { code:'P0116', name:'Engine Coolant Temperature Sensor Range/Performance', cat:'sensors', sev:'med',
    causes:['Faulty coolant temperature sensor','Stuck-open thermostat','Air pocket in cooling system','Wiring fault'],
    symptoms:['Temperature gauge reading wrong','Poor fuel economy when cold','Check engine light'],
    solutions:['Test CTS resistance vs temperature','Check thermostat operation','Bleed cooling system','Replace CTS'],
    diy:true, avg_cost:'$30–$200' },

  { code:'P0117', name:'Engine Coolant Temperature Sensor Low Input', cat:'sensors', sev:'med',
    causes:['Short to ground in CTS wiring','Coolant temperature sensor failure','Corroded connector'],
    symptoms:['Temperature gauge pegged cold or hot','Rich fuel mixture','Poor cold performance'],
    solutions:['Inspect CTS wiring','Check connector corrosion','Replace CTS'],
    diy:true, avg_cost:'$25–$150' },

  { code:'P0118', name:'Engine Coolant Temperature Sensor High Input', cat:'sensors', sev:'med',
    causes:['Open circuit in CTS wiring','Failed CTS sensor','Connector issue'],
    symptoms:['Temperature gauge reads incorrectly','Engine runs rich','Fan may not operate correctly'],
    solutions:['Check CTS wiring continuity','Inspect sensor connector','Replace CTS'],
    diy:true, avg_cost:'$25–$150' },

  { code:'P0122', name:'Throttle Position Sensor (TPS) Circuit Low Input', cat:'sensors', sev:'med',
    causes:['Faulty TPS sensor','Open circuit in wiring','Loose throttle body connector','ECM fault'],
    symptoms:['Hesitation on acceleration','Idle surge','Possible stalling','Check engine light'],
    solutions:['Inspect TPS wiring and connector','Check reference voltage (5V)','Replace TPS sensor'],
    diy:true, avg_cost:'$30–$250' },

  { code:'P0123', name:'Throttle Position Sensor (TPS) Circuit High Input', cat:'sensors', sev:'med',
    causes:['Short to voltage in TPS wiring','Faulty TPS','ECM fault'],
    symptoms:['High idle','Hesitation','Check engine light'],
    solutions:['Check TPS signal wire for short','Test TPS sweep voltage','Replace TPS'],
    diy:true, avg_cost:'$30–$250' },

  { code:'P0133', name:'O2 Sensor Slow Response Bank 1 Sensor 1', cat:'sensors', sev:'med',
    causes:['Aging oxygen sensor','Exhaust leak near sensor','Engine running lean','Contaminated sensor'],
    symptoms:['Check engine light','Slightly poor fuel economy'],
    solutions:['Check for exhaust leaks','Test O2 sensor switching frequency','Replace O2 sensor'],
    diy:true, avg_cost:'$100–$300' },

  { code:'P0136', name:'O2 Sensor Circuit Malfunction Bank 1 Sensor 2', cat:'sensors', sev:'med',
    causes:['Failed downstream O2 sensor','Wiring damage from exhaust heat','Connector corrosion'],
    symptoms:['Check engine light','Potential increased emissions'],
    solutions:['Inspect downstream O2 sensor wiring','Test sensor signal','Replace O2 sensor'],
    diy:true, avg_cost:'$80–$250' },

  { code:'P0141', name:'O2 Sensor Heater Circuit Malfunction Bank 1 Sensor 2', cat:'sensors', sev:'low',
    causes:['Blown fuse','Failed heater in downstream O2 sensor','Wiring damage'],
    symptoms:['Check engine light','Minor cold-start emissions increase'],
    solutions:['Check O2 heater fuse','Test heater resistance (10–20 ohms)','Replace O2 sensor'],
    diy:true, avg_cost:'$50–$200' },

  { code:'P0175', name:'System Too Rich Bank 2', cat:'fuel', sev:'med',
    causes:['Leaking fuel injectors Bank 2','Faulty MAF sensor','Stuck-open fuel pressure regulator','Coolant temp sensor fault'],
    symptoms:['Black smoke','Fuel smell','Rough idle','Poor fuel economy'],
    solutions:['Clean or replace fuel injectors','Replace MAF sensor','Test fuel pressure regulator','Check CTS'],
    diy:true, avg_cost:'$80–$500' },

  { code:'P0201', name:'Injector Circuit Open Cylinder 1', cat:'fuel', sev:'high',
    causes:['Open circuit in injector wiring','Failed fuel injector','Bad injector connector','ECM injector driver failure'],
    symptoms:['Cylinder 1 misfire','Rough idle','Check engine light','Loss of power'],
    solutions:['Test injector resistance (12–16 ohms)','Inspect injector wiring','Replace injector','Check ECM output'],
    diy:true, avg_cost:'$100–$400' },

  { code:'P0202', name:'Injector Circuit Open Cylinder 2', cat:'fuel', sev:'high',
    causes:['Failed injector','Open wiring','Connector fault'],
    symptoms:['Cylinder 2 misfire','Rough idle','Power loss'],
    solutions:['Test injector resistance','Inspect wiring','Replace injector'],
    diy:true, avg_cost:'$100–$400' },

  { code:'P0300', name:'Random/Multiple Cylinder Misfire Detected', cat:'engine', sev:'high',
    causes:['Worn spark plugs','Failed ignition coils','Low fuel pressure','Vacuum leak'],
    symptoms:['Rough idle','Flashing check engine light','Loss of power'],
    solutions:['Replace spark plugs','Test ignition coils','Check fuel pressure','Inspect vacuum lines'],
    diy:true, avg_cost:'$50–$400' },

  { code:'P0325', name:'Knock Sensor 1 Circuit Malfunction', cat:'sensors', sev:'med',
    causes:['Failed knock sensor','Damaged wiring harness','Loose sensor mounting','Engine knock/detonation'],
    symptoms:['Check engine light','Reduced engine performance (timing retarded)','Slightly poor fuel economy'],
    solutions:['Check knock sensor mounting torque','Inspect wiring','Replace knock sensor','Check for actual engine knock'],
    diy:true, avg_cost:'$80–$350', tip:'The sensor is often under the intake manifold — labor can be significant on some engines.' },

  { code:'P0330', name:'Knock Sensor 2 Circuit Malfunction', cat:'sensors', sev:'med',
    causes:['Failed knock sensor Bank 2','Wiring fault','Loose sensor'],
    symptoms:['Check engine light','Reduced timing advance','Poor performance under load'],
    solutions:['Check sensor mounting','Inspect wiring','Replace knock sensor'],
    diy:true, avg_cost:'$80–$350' },

  { code:'P0336', name:'Crankshaft Position Sensor A Circuit Range/Performance', cat:'sensors', sev:'high',
    causes:['Damaged CKP sensor tone wheel','Air gap out of spec','Weak CKP sensor signal','Wiring interference'],
    symptoms:['Intermittent stalling','Hard starting','Engine hesitation'],
    solutions:['Inspect tone wheel for damage','Check CKP air gap','Inspect sensor wiring','Replace CKP sensor'],
    diy:true, avg_cost:'$80–$350' },

  { code:'P0341', name:'Camshaft Position Sensor Circuit Range/Performance Bank 1', cat:'sensors', sev:'high',
    causes:['Timing chain stretch','Damaged reluctor wheel','Weak cam sensor signal','Oil contamination of sensor'],
    symptoms:['Hard starting','Intermittent stalling','Check engine light'],
    solutions:['Inspect timing chain','Check reluctor wheel','Replace cam sensor','Check for oil leaks near sensor'],
    diy:true, avg_cost:'$80–$500' },

  { code:'P0401', name:'EGR Flow Insufficient Detected', cat:'emissions', sev:'med',
    causes:['Clogged EGR valve','Blocked EGR passages','Failed EGR valve actuator','Vacuum line failure'],
    symptoms:['Check engine light','Occasional rough idle','Increased NOx emissions (not visible)'],
    solutions:['Clean EGR valve and passages with carburetor cleaner','Test EGR valve operation','Replace EGR valve','Check vacuum lines'],
    diy:true, avg_cost:'$50–$400', tip:'On many vehicles the EGR passage to the intake manifold gets heavily clogged — cleaning the passage is as important as the valve itself.' },

  { code:'P0402', name:'EGR Flow Excessive Detected', cat:'emissions', sev:'med',
    causes:['EGR valve stuck open','Failed EGR pressure sensor','Leaking EGR system'],
    symptoms:['Rough idle','Stalling at idle','Check engine light'],
    solutions:['Test EGR valve for stuck-open condition','Inspect EGR feedback sensor','Replace EGR valve'],
    diy:true, avg_cost:'$80–$400' },

  { code:'P0404', name:'EGR Circuit Range/Performance', cat:'emissions', sev:'med',
    causes:['EGR valve stuck','Carbon buildup on valve pintle','Failed EGR position sensor','Vacuum leak at EGR'],
    symptoms:['Rough idle','Check engine light','Occasionally poor throttle response'],
    solutions:['Remove and clean EGR valve','Test position sensor','Replace EGR valve if needed'],
    diy:true, avg_cost:'$80–$400' },

  { code:'P0411', name:'Secondary Air Injection System Flow Incorrect', cat:'emissions', sev:'low',
    causes:['Faulty AIR pump','Clogged check valves','Failed AIR solenoid','Vacuum leak in AIR system'],
    symptoms:['Check engine light','Possible cold start rough idle'],
    solutions:['Test AIR pump operation','Inspect check valves','Replace AIR solenoid','Check vacuum hoses'],
    diy:false, avg_cost:'$150–$700' },

  { code:'P0440', name:'Evaporative Emission Control System Malfunction', cat:'emissions', sev:'low',
    causes:['Loose or missing fuel cap','Cracked EVAP hose','Faulty purge valve','Faulty vent valve'],
    symptoms:['Check engine light','Fuel odor','Failed emissions test'],
    solutions:['Check and tighten fuel cap','Inspect all EVAP hoses for cracks','Test purge valve','Test vent valve'],
    diy:true, avg_cost:'$0–$300' },

  { code:'P0446', name:'EVAP Control System Vent Control Circuit', cat:'emissions', sev:'low',
    causes:['Failed EVAP vent valve','Vent valve solenoid wiring fault','Charcoal canister clogged','Debris in vent valve'],
    symptoms:['Check engine light','Difficulty refueling','Fuel odor'],
    solutions:['Test vent valve solenoid','Inspect for debris in valve','Check wiring','Replace vent valve'],
    diy:true, avg_cost:'$50–$250' },

  { code:'P0452', name:'Fuel Tank Pressure Sensor Circuit Low Input', cat:'emissions', sev:'low',
    causes:['Failed FTP sensor','Wiring short to ground','Connector corrosion','Sensor clogged with fuel'],
    symptoms:['Check engine light','EVAP system malfunction'],
    solutions:['Inspect FTP sensor connector','Test sensor voltage','Replace FTP sensor'],
    diy:true, avg_cost:'$40–$200' },

  { code:'P0453', name:'Fuel Tank Pressure Sensor Circuit High Input', cat:'emissions', sev:'low',
    causes:['FTP sensor wiring short to voltage','Failed sensor','Blocked sensor port'],
    symptoms:['Check engine light','Possible refueling difficulty'],
    solutions:['Inspect wiring','Test sensor','Replace FTP sensor'],
    diy:true, avg_cost:'$40–$200' },

  /* ═══════════════════ TRANSMISSION (more) ═══════════════════ */
  { code:'P0705', name:'Transmission Range Sensor Circuit Malfunction', cat:'transmission', sev:'med',
    causes:['Faulty neutral safety switch','Wiring fault','Misadjusted selector lever','Failed TR sensor'],
    symptoms:['Vehicle does not start in park','Wrong gear indicated','Erratic shifting'],
    solutions:['Check TR sensor adjustment','Inspect wiring','Replace TR sensor','Adjust shift linkage'],
    diy:true, avg_cost:'$100–$400' },

  { code:'P0710', name:'Transmission Fluid Temperature Sensor Circuit', cat:'transmission', sev:'med',
    causes:['Failed TFT sensor','Wiring fault','Connector corrosion','Low fluid causing overheating'],
    symptoms:['Check engine light','Transmission going into limp mode','Erratic shift quality'],
    solutions:['Check transmission fluid level and condition','Inspect TFT sensor','Replace sensor','Flush transmission if fluid is dark'],
    diy:true, avg_cost:'$100–$400' },

  { code:'P0715', name:'Input/Turbine Speed Sensor Circuit Malfunction', cat:'transmission', sev:'high',
    causes:['Failed input speed sensor','Damaged tone ring','Wiring fault','Metal debris on sensor tip'],
    symptoms:['Harsh or erratic shifts','Torque converter lockup issues','Check engine light','Transmission slipping'],
    solutions:['Inspect sensor and tone ring','Clean sensor tip','Check wiring','Replace input speed sensor'],
    diy:true, avg_cost:'$100–$400' },

  { code:'P0720', name:'Output Speed Sensor Circuit Malfunction', cat:'transmission', sev:'high',
    causes:['Failed output speed sensor','Tone ring damage','Wiring fault'],
    symptoms:['Erratic speedometer','Harsh shifting','Transmission limp mode'],
    solutions:['Inspect tone ring','Check wiring','Replace output speed sensor'],
    diy:true, avg_cost:'$100–$400' },

  { code:'P0731', name:'Gear 1 Incorrect Ratio', cat:'transmission', sev:'high',
    causes:['Worn clutch pack 1st gear','Shift solenoid fault','Valve body issue','Low transmission fluid'],
    symptoms:['Transmission slipping in 1st gear','Harsh engagement','Check engine light'],
    solutions:['Check fluid level and condition','Test shift solenoids','Valve body service','Rebuild or replace transmission'],
    diy:false, avg_cost:'$300–$2500' },

  { code:'P0732', name:'Gear 2 Incorrect Ratio', cat:'transmission', sev:'high',
    causes:['Worn 2nd gear clutch pack','Shift solenoid fault','Fluid contamination'],
    symptoms:['Slipping in 2nd gear','Harsh 1-2 shift'],
    solutions:['Check fluid','Test solenoids','Valve body inspection','Transmission service'],
    diy:false, avg_cost:'$300–$2500' },

  { code:'P0741', name:'Torque Converter Clutch Circuit Performance', cat:'transmission', sev:'med',
    causes:['Failed TCC solenoid','Worn TCC clutch','Valve body wear','Low fluid pressure'],
    symptoms:['Shudder at highway speed','Poor fuel economy','Lockup not engaging or releasing'],
    solutions:['Check fluid level and condition','Test TCC solenoid','Service valve body','Replace torque converter'],
    diy:false, avg_cost:'$200–$1500' },

  { code:'P0750', name:'Shift Solenoid A Malfunction', cat:'transmission', sev:'high',
    causes:['Failed shift solenoid','Wiring open/short','Valve body clog','Low fluid pressure'],
    symptoms:['Limp mode','Stuck in one gear','Harsh or no shifting','Check engine light'],
    solutions:['Check fluid level','Inspect solenoid resistance','Replace solenoid A','Flush transmission'],
    diy:false, avg_cost:'$150–$800' },

  { code:'P0755', name:'Shift Solenoid B Malfunction', cat:'transmission', sev:'high',
    causes:['Failed solenoid B','Wiring fault','Valve body wear','Contaminated fluid'],
    symptoms:['Limp mode','Wrong gear engagement','Check engine light'],
    solutions:['Check fluid','Test solenoid B','Replace solenoid','Service transmission'],
    diy:false, avg_cost:'$150–$800' },

  /* ═══════════════════ FUEL SYSTEM (more) ═══════════════════ */
  { code:'P0088', name:'Fuel Rail/System Pressure Too High', cat:'fuel', sev:'high',
    causes:['Failed fuel pressure regulator stuck closed','Pinched fuel return line','Faulty fuel pressure sensor','Clogged fuel return'],
    symptoms:['Black smoke from exhaust','Rich running','Hard starting when hot','Fuel smell'],
    solutions:['Test fuel pressure with gauge','Inspect fuel return line','Test fuel pressure regulator','Replace regulator'],
    diy:true, avg_cost:'$80–$400' },

  { code:'P0089', name:'Fuel Pressure Regulator 1 Performance', cat:'fuel', sev:'high',
    causes:['Faulty fuel pressure regulator','Weak fuel pump','Clogged fuel filter','Leaking injectors'],
    symptoms:['Rough idle','Hesitation under load','Check engine light','Possibly stalling'],
    solutions:['Test fuel pressure','Replace fuel filter','Test fuel pump','Replace fuel pressure regulator'],
    diy:true, avg_cost:'$80–$500' },

  { code:'P0090', name:'Fuel Pressure Regulator 1 Control Circuit', cat:'fuel', sev:'high',
    causes:['Failed FPR solenoid','Wiring fault','ECM fault'],
    symptoms:['Check engine light','Fuel pressure concerns','Possible stalling'],
    solutions:['Inspect FPR wiring','Test solenoid resistance','Replace FPR','Check ECM output'],
    diy:true, avg_cost:'$80–$400' },

  { code:'P0093', name:'Fuel System Leak Detected — Large Leak', cat:'fuel', sev:'high',
    causes:['Major HPFP failure','Cracked fuel line','Injector seal failure','Return line disconnected'],
    symptoms:['Strong fuel smell','Possible stalling','Check engine light'],
    solutions:['Inspect all fuel lines','Check injector seals','Test high-pressure fuel pump','Pressure decay test'],
    diy:false, avg_cost:'$200–$1500' },

  { code:'P0172', name:'System Too Rich Bank 1', cat:'fuel', sev:'med',
    causes:['Leaking fuel injectors','Faulty MAF sensor over-reading','Stuck-open fuel pressure regulator','Coolant temp sensor fault'],
    symptoms:['Black exhaust smoke','Fuel smell','Poor fuel economy','Rough idle'],
    solutions:['Clean or replace MAF sensor','Test injectors for leakdown','Check FPR','Replace CTS if faulty'],
    diy:true, avg_cost:'$50–$500' },

  /* ═══════════════════ IGNITION (more) ═══════════════════ */
  { code:'P0353', name:'Ignition Coil C Primary/Secondary Circuit', cat:'ignition', sev:'high',
    causes:['Failed ignition coil cylinder 3','Open or short in coil wiring','ECM coil driver failure','Damaged spark plug boot'],
    symptoms:['Cylinder 3 misfire','Rough idle','Check engine light'],
    solutions:['Test coil resistance','Swap coil to another cylinder','Inspect wiring','Replace coil'],
    diy:true, avg_cost:'$50–$250' },

  { code:'P0354', name:'Ignition Coil D Primary/Secondary Circuit', cat:'ignition', sev:'high',
    causes:['Failed ignition coil D','Wiring open/short','Boot damage'],
    symptoms:['Cylinder 4 misfire','Check engine light','Rough running'],
    solutions:['Test coil resistance','Swap test coil','Check wiring','Replace coil'],
    diy:true, avg_cost:'$50–$250' },

  { code:'P0355', name:'Ignition Coil E Primary/Secondary Circuit', cat:'ignition', sev:'high',
    causes:['Failed ignition coil E','Wiring fault'],
    symptoms:['Cylinder 5 misfire','Rough idle'],
    solutions:['Swap test coil','Inspect wiring','Replace coil'],
    diy:true, avg_cost:'$50–$250' },

  { code:'P0356', name:'Ignition Coil F Primary/Secondary Circuit', cat:'ignition', sev:'high',
    causes:['Failed ignition coil F','Wiring fault'],
    symptoms:['Cylinder 6 misfire','Rough running'],
    solutions:['Swap test coil','Inspect wiring','Replace coil'],
    diy:true, avg_cost:'$50–$250' },

  { code:'P0357', name:'Ignition Coil G Primary/Secondary Circuit', cat:'ignition', sev:'high',
    causes:['Failed ignition coil G','Wiring fault'],
    symptoms:['Cylinder 7 misfire','Rough running'],
    solutions:['Swap test coil','Inspect wiring','Replace coil'],
    diy:true, avg_cost:'$50–$250' },

  { code:'P0358', name:'Ignition Coil H Primary/Secondary Circuit', cat:'ignition', sev:'high',
    causes:['Failed ignition coil H','Wiring fault'],
    symptoms:['Cylinder 8 misfire','Rough running'],
    solutions:['Swap test coil','Inspect wiring','Replace coil'],
    diy:true, avg_cost:'$50–$250' },

  { code:'P0506', name:'Idle Air Control System RPM Too Low', cat:'engine', sev:'med',
    causes:['Dirty throttle body','Failed IAC valve','Vacuum leak','Carbon buildup on throttle plate'],
    symptoms:['Low idle','Stalling at stops','Rough idle'],
    solutions:['Clean throttle body','Clean IAC valve','Check for vacuum leaks','Replace IAC valve'],
    diy:true, avg_cost:'$30–$300' },

  { code:'P0507', name:'Idle Control System RPM Too High', cat:'engine', sev:'med',
    causes:['Vacuum leak causing high idle','Stuck IAC valve open','Throttle plate not closing fully','Air leak past throttle body'],
    symptoms:['High idle (above 1200 rpm)','Engine revs too fast','Poor fuel economy'],
    solutions:['Spray carb cleaner around vacuum lines to find leak','Clean throttle body','Test IAC valve','Check throttle cable/pedal for binding'],
    diy:true, avg_cost:'$30–$300' },

  /* ═══════════════════ ABS / BRAKES ═══════════════════ */
  { code:'C0031', name:'Right Front Wheel Speed Sensor Circuit', cat:'abs', sev:'high',
    causes:['Failed wheel speed sensor','Damaged wiring from road debris','Air gap too large','Tone ring damage'],
    symptoms:['ABS light on','Traction control disabled','ABS not functioning'],
    solutions:['Inspect sensor wiring along axle','Check air gap (0.5–1.5mm)','Inspect tone ring for missing teeth','Replace wheel speed sensor'],
    diy:true, avg_cost:'$100–$350' },

  { code:'C0034', name:'Right Rear Wheel Speed Sensor Circuit', cat:'abs', sev:'high',
    causes:['Failed wheel speed sensor','Wiring damage','Torn bearing ABS ring','Corroded connector'],
    symptoms:['ABS warning light','Stability control off','ABS inactive'],
    solutions:['Inspect rear sensor and wiring','Check bearing-integrated tone ring','Replace sensor'],
    diy:true, avg_cost:'$100–$400' },

  { code:'C0037', name:'Left Rear Wheel Speed Sensor Circuit', cat:'abs', sev:'high',
    causes:['Failed left rear WSS','Wiring damage','Bearing tone ring damaged'],
    symptoms:['ABS light','Traction control off'],
    solutions:['Check sensor and harness','Inspect tone ring','Replace sensor'],
    diy:true, avg_cost:'$100–$400' },

  { code:'C0040', name:'Right Front Wheel Speed Sensor Signal Plausibility', cat:'abs', sev:'high',
    causes:['Intermittent WSS fault','Tone ring damage','WSS air gap issue','Bearing play causing tone ring wobble'],
    symptoms:['Intermittent ABS activation','ABS light'],
    solutions:['Inspect tone ring','Check wheel bearing play','Verify air gap','Replace WSS'],
    diy:true, avg_cost:'$100–$500' },

  { code:'C0051', name:'Steering Wheel Angle Sensor Circuit', cat:'abs', sev:'med',
    causes:['Failed steering angle sensor','Wiring fault','Needs calibration after alignment','Module fault'],
    symptoms:['Stability control warning','ESC disabled','Possible ABS light'],
    solutions:['Recalibrate sensor after alignment','Inspect wiring','Replace sensor','Reprogram module'],
    diy:false, avg_cost:'$150–$600' },

  { code:'C0061', name:'ABS Solenoid 1 A Circuit', cat:'abs', sev:'high',
    causes:['Failed ABS solenoid','EBCM fault','Wiring fault in ABS modulator harness'],
    symptoms:['ABS inoperative','ABS warning light','Possible longer stopping distances'],
    solutions:['Test solenoid resistance','Inspect EBCM wiring','Replace ABS modulator or EBCM'],
    diy:false, avg_cost:'$300–$1200' },

  /* ═══════════════════ AIRBAG / SRS ═══════════════════ */
  { code:'B0001', name:'Driver Frontal Stage 1 Squib Circuit Resistance Low', cat:'airbag', sev:'high',
    causes:['Faulty driver airbag clockspring','Corroded spiral cable','Short circuit in airbag wiring','Aftermarket steering wheel without clockspring'],
    symptoms:['SRS airbag light on','Airbag will not deploy in collision'],
    solutions:['NEVER probe airbag circuits with test light — use scan tool only','Replace clockspring','Inspect airbag wiring','Replace airbag module'],
    diy:false, avg_cost:'$200–$900', tip:'Airbag circuits must never be probed with standard electrical test equipment — always use an SRS-capable scan tool.' },

  { code:'B0002', name:'Driver Frontal Stage 2 Squib Circuit Resistance Low', cat:'airbag', sev:'high',
    causes:['Faulty airbag module','Wiring fault to stage 2 inflator','Clockspring failure'],
    symptoms:['SRS warning light'],
    solutions:['Scan with SRS-capable tool','Inspect wiring','Replace clockspring or airbag'],
    diy:false, avg_cost:'$300–$1000' },

  { code:'B0010', name:'Passenger Frontal Stage 1 Squib Circuit Resistance Low', cat:'airbag', sev:'high',
    causes:['Failed passenger airbag squib','Wiring harness damage under dashboard','Connector corrosion'],
    symptoms:['SRS airbag light on'],
    solutions:['SRS scan tool diagnosis only','Inspect harness under dash','Replace passenger airbag'],
    diy:false, avg_cost:'$300–$1200' },

  { code:'B0051', name:'Side Impact Sensor Left Front — Circuit Low', cat:'airbag', sev:'high',
    causes:['Failed side impact sensor','Wiring damage from accident','Corroded connector'],
    symptoms:['Airbag warning light on'],
    solutions:['Scan with SRS tool','Inspect sensor wiring','Replace side impact sensor'],
    diy:false, avg_cost:'$200–$700' },

  /* ═══════════════════ HVAC ═══════════════════ */
  { code:'B1001', name:'HVAC Control Module Internal Failure', cat:'hvac', sev:'med',
    causes:['Faulty HVAC control head','Software corruption','Power or ground issue to module'],
    symptoms:['AC/heat not responding to controls','Blank display','Random mode changes'],
    solutions:['Check power and ground to HVAC module','Software update if available','Replace HVAC control module'],
    diy:false, avg_cost:'$200–$800' },

  { code:'B1004', name:'Blend Door Actuator Position Fault', cat:'hvac', sev:'med',
    causes:['Failed blend door actuator','Broken blend door','Actuator gear stripped','Wiring fault'],
    symptoms:['Stuck on hot or cold','Clicking noise behind dash','Temperature not changing'],
    solutions:['Test actuator with scan tool','Inspect actuator mechanism','Replace blend door actuator'],
    diy:true, avg_cost:'$80–$400', tip:'The clicking noise behind the dash at startup is almost always a stripped blend door actuator gear — a very common failure.' },

  { code:'B1006', name:'Evaporator Temperature Sensor Circuit', cat:'hvac', sev:'low',
    causes:['Failed evaporator temp sensor','Wiring fault','Connector corrosion'],
    symptoms:['AC blows warm intermittently','AC cuts out too early'],
    solutions:['Inspect sensor wiring','Test sensor resistance','Replace sensor'],
    diy:true, avg_cost:'$50–$200' },

  /* ═══════════════════ ELECTRICAL (more) ═══════════════════ */
  { code:'P0563', name:'System Voltage High', cat:'electrical', sev:'high',
    causes:['Faulty voltage regulator in alternator','Failed ECM regulator circuit','Battery issue causing voltage spike'],
    symptoms:['Battery warning light','Electronics behaving erratically','Possible blown fuses','Burnt electrical smell'],
    solutions:['Test charging voltage (should be 13.5–14.8V)','Replace alternator with bad regulator','Check battery condition'],
    diy:true, avg_cost:'$100–$600' },

  { code:'P0600', name:'Serial Communication Link Circuit', cat:'network', sev:'high',
    causes:['Failed ECM','Wiring fault on CAN bus','Damaged communication harness','Corroded ground connection'],
    symptoms:['Multiple system faults','Modules not communicating','Possible no-start'],
    solutions:['Check battery and grounds','Inspect CAN bus wiring','Test ECM power and ground','Replace ECM if confirmed failed'],
    diy:false, avg_cost:'$300–$1500' },

  { code:'P0606', name:'PCM Processor Fault', cat:'electrical', sev:'high',
    causes:['Internal PCM/ECM failure','Voltage spike damage','Software corruption','Overheating of ECM'],
    symptoms:['Multiple fault codes','Possible no-start','Erratic engine behavior'],
    solutions:['Check for TSBs and software updates','Verify power and ground to ECM','Replace or reprogram PCM'],
    diy:false, avg_cost:'$400–$1500' },

  /* ═══════════════════ NETWORK / CAN BUS (more) ═══════════════════ */
  { code:'U0001', name:'High Speed CAN Communication Bus', cat:'network', sev:'high',
    causes:['Broken CAN bus wiring','Module with internal fault pulling bus down','Corroded splice connector','Failed gateway module'],
    symptoms:['Multiple warning lights','Multiple systems offline','Possible no-start'],
    solutions:['Measure CAN bus resistance (should be ~60 ohms between CAN H and L)','Inspect main CAN harness','Disconnect modules one at a time to isolate fault'],
    diy:false, avg_cost:'$200–$2000', tip:'Check CAN bus resistance first: 60 ohms = normal, 120 ohms = one terminator missing, 30 ohms = extra module on bus.' },

  { code:'U0101', name:'Lost Communication With TCM', cat:'network', sev:'high',
    causes:['Failed TCM (Transmission Control Module)','CAN bus wiring fault','Power or ground loss to TCM','ECM fault'],
    symptoms:['Transmission in limp mode','Check engine light','Erratic shifting or no shifting'],
    solutions:['Check TCM power and ground','Inspect CAN wiring to TCM','Check TCM connector for corrosion','Replace TCM'],
    diy:false, avg_cost:'$200–$1000' },

  { code:'U0121', name:'Lost Communication With ABS Control Module', cat:'network', sev:'high',
    causes:['Failed ABS module','CAN bus wiring fault','Power or ground loss to EBCM'],
    symptoms:['ABS light','Traction control off','Stability control off'],
    solutions:['Check EBCM power and ground','Test CAN wiring','Replace EBCM'],
    diy:false, avg_cost:'$200–$1000' },

  { code:'U0140', name:'Lost Communication With Body Control Module', cat:'network', sev:'high',
    causes:['Failed BCM','Power or ground fault to BCM','CAN wiring fault','BCM programming loss'],
    symptoms:['Multiple body electronics not working','Door locks/windows inoperative','Lighting issues'],
    solutions:['Check BCM fuses and grounds','Inspect CAN wiring','Reprogram or replace BCM'],
    diy:false, avg_cost:'$200–$1200' },

  { code:'U0155', name:'Lost Communication With Instrument Panel Cluster', cat:'network', sev:'med',
    causes:['Failed instrument cluster','CAN bus wiring fault','Power loss to cluster'],
    symptoms:['Blank instrument cluster','No gauges','Warning lights not working'],
    solutions:['Check cluster fuse and power','Inspect CAN wiring to cluster','Replace instrument cluster'],
    diy:false, avg_cost:'$200–$800' },

  /* ═══════════════════ EXHAUST (more) ═══════════════════ */
  { code:'P0421', name:'Warm Up Catalyst Efficiency Below Threshold Bank 1', cat:'exhaust', sev:'med',
    causes:['Aged or poisoned catalytic converter','O2 sensor fault giving false reading','Exhaust leak before catalyst','Engine oil or coolant burning'],
    symptoms:['Check engine light','Failed emissions test'],
    solutions:['Verify with known-good O2 sensors','Check for exhaust leaks before cat','Test for oil or coolant burning','Replace catalytic converter'],
    diy:false, avg_cost:'$500–$2000' },

  { code:'P0431', name:'Warm Up Catalyst Efficiency Below Threshold Bank 2', cat:'exhaust', sev:'med',
    causes:['Aged catalytic converter Bank 2','O2 sensor issue','Exhaust leak','Engine misfire damaging cat'],
    symptoms:['Check engine light','Emissions test failure'],
    solutions:['Fix any misfires first','Check O2 sensors Bank 2','Inspect exhaust for leaks','Replace catalytic converter Bank 2'],
    diy:false, avg_cost:'$500–$2000' },

  { code:'P0480', name:'Cooling Fan 1 Control Circuit', cat:'electrical', sev:'high',
    causes:['Failed cooling fan relay','Fan motor failure','Wiring open/short to fan','ECM fan control circuit failure'],
    symptoms:['Engine overheating at idle','AC blows warm at idle','Fan not running'],
    solutions:['Test cooling fan relay','Test fan motor directly','Inspect fan wiring','Replace relay or fan motor'],
    diy:true, avg_cost:'$50–$400' },

  { code:'P0481', name:'Cooling Fan 2 Control Circuit', cat:'electrical', sev:'high',
    causes:['Failed secondary fan relay','Fan motor failure','Wiring fault'],
    symptoms:['Overheating in traffic','AC performance degraded'],
    solutions:['Test relay','Test fan motor','Inspect wiring','Replace as needed'],
    diy:true, avg_cost:'$50–$400' },

  { code:'P0491', name:'Secondary Air Injection System Insufficient Flow Bank 1', cat:'emissions', sev:'low',
    causes:['Failed AIR pump','Clogged check valve','Failed AIR solenoid','Vacuum line leak'],
    symptoms:['Check engine light','Emissions test failure'],
    solutions:['Test AIR pump','Inspect check valves','Test solenoid','Repair vacuum lines'],
    diy:false, avg_cost:'$200–$900' },

  /* ═══════════════════ SENSORS (more) ═══════════════════ */
  { code:'P0500', name:'Vehicle Speed Sensor Malfunction', cat:'sensors', sev:'med',
    causes:['Failed VSS','Damaged VSS wiring','Tone ring damage on output shaft','ABS module fault'],
    symptoms:['Speedometer not working','Transmission shift issues','Cruise control inoperative','ABS light possible'],
    solutions:['Inspect VSS and wiring','Check tone ring','Replace VSS sensor','Check for ABS module faults'],
    diy:true, avg_cost:'$80–$350' },

  { code:'P0501', name:'Vehicle Speed Sensor Range/Performance', cat:'sensors', sev:'med',
    causes:['Intermittent VSS signal','Tone ring damage','Wiring harness issue'],
    symptoms:['Intermittent speedometer drop','Erratic shifting'],
    solutions:['Check VSS wiring for intermittent fault','Inspect tone ring','Replace VSS'],
    diy:true, avg_cost:'$80–$350' },

  { code:'P0560', name:'System Voltage Circuit Malfunction', cat:'electrical', sev:'high',
    causes:['Corroded battery terminals','Failing alternator','Bad battery','High resistance in charging circuit'],
    symptoms:['Multiple intermittent faults','Battery light','Dim lights'],
    solutions:['Load test battery','Test alternator output','Clean battery terminals','Check charging circuit resistance'],
    diy:true, avg_cost:'$50–$500' },

  { code:'P0571', name:'Cruise/Brake Switch A Circuit', cat:'electrical', sev:'low',
    causes:['Faulty brake light switch','Misadjusted brake switch','Wiring fault to switch'],
    symptoms:['Cruise control not engaging','Brake lights possibly not working','Check engine light'],
    solutions:['Check and adjust brake light switch','Inspect switch wiring','Replace brake switch'],
    diy:true, avg_cost:'$20–$150' },
]
