export type LangCode = 'en' | 'ar' | 'es' | 'fr' | 'de' | 'pt' | 'hi'

export const LANGUAGES = [
  { code: 'en' as LangCode, label: 'English',   flag: '🇺🇸' },
  { code: 'ar' as LangCode, label: 'العربية',   flag: '🇸🇦', rtl: true },
  { code: 'es' as LangCode, label: 'Español',   flag: '🇪🇸' },
  { code: 'fr' as LangCode, label: 'Français',  flag: '🇫🇷' },
  { code: 'de' as LangCode, label: 'Deutsch',   flag: '🇩🇪' },
  { code: 'pt' as LangCode, label: 'Português', flag: '🇧🇷' },
  { code: 'hi' as LangCode, label: 'हिन्दी',    flag: '🇮🇳' },
]

const T: Record<LangCode, Record<string, string>> = {
  en: { categories:'Categories', allCodes:'All Codes', about:'About', contact:'Contact', lookup:'🔍 Lookup', tagline:'🔧 Free Diagnostic Tool', hero1:'DECODE ANY', hero2:'FAULT CODE', heroSub:'Instant OBD2 diagnostic trouble code lookup with AI-powered causes, symptoms, repair guides, and estimated costs.', searchPlaceholder:'Type a code: P0300, P0420, or describe a symptom…', browseCategory:'Browse by', category:'Category', viewAll:'View all categories →', allCodesPlus:'2,600+', results:'Results for', codes:'codes', code:'code', noResults:'No codes found. Try a different search term.', viewDetails:'View details →', severity:'All Severity', critical:'🔴 Critical', moderate:'🟡 Moderate', minor:'🟢 Minor', disclaimer:'Data is for reference only. Always consult a certified technician for safety-critical repairs.', footerDesc:"The world's most comprehensive OBD2 fault code database — free, multilingual, and AI-powered.", quickLinks:'Quick Links', popularCodes:'Popular Codes' },
  ar: { categories:'الفئات', allCodes:'كل الرموز', about:'من نحن', contact:'اتصل بنا', lookup:'🔍 بحث', tagline:'🔧 أداة تشخيص مجانية', hero1:'فك تشفير أي', hero2:'رمز عطل', heroSub:'بحث فوري في رموز أعطال OBD2 مع أسباب مدعومة بالذكاء الاصطناعي وأعراض وأدلة إصلاح.', searchPlaceholder:'اكتب رمزًا: P0300، P0420، أو صف العرض…', browseCategory:'تصفح حسب', category:'الفئة', viewAll:'← عرض كل الفئات', allCodesPlus:'+2,600', results:'نتائج', codes:'رموز', code:'رمز', noResults:'لم يتم العثور على رموز.', viewDetails:'← عرض التفاصيل', severity:'كل الدرجات', critical:'🔴 حرج', moderate:'🟡 متوسط', minor:'🟢 بسيط', disclaimer:'البيانات للرجوع إليها فقط.', footerDesc:'قاعدة بيانات رموز أعطال OBD2 الأكثر شمولاً — مجانية ومتعددة اللغات.', quickLinks:'روابط سريعة', popularCodes:'الرموز الشائعة' },
  es: { categories:'Categorías', allCodes:'Todos los códigos', about:'Acerca de', contact:'Contacto', lookup:'🔍 Buscar', tagline:'🔧 Herramienta gratuita', hero1:'DECODIFICA CUALQUIER', hero2:'CÓDIGO DE FALLA', heroSub:'Búsqueda instantánea de códigos OBD2 con causas, síntomas y guías de reparación.', searchPlaceholder:'Escribe un código: P0300, P0420, o describe un síntoma…', browseCategory:'Buscar por', category:'Categoría', viewAll:'Ver todas las categorías →', allCodesPlus:'+2,600', results:'Resultados para', codes:'códigos', code:'código', noResults:'No se encontraron códigos.', viewDetails:'Ver detalles →', severity:'Toda gravedad', critical:'🔴 Crítico', moderate:'🟡 Moderado', minor:'🟢 Menor', disclaimer:'Los datos son solo de referencia.', footerDesc:'La base de datos OBD2 más completa del mundo — gratuita y multilingüe.', quickLinks:'Enlaces rápidos', popularCodes:'Códigos populares' },
  fr: { categories:'Catégories', allCodes:'Tous les codes', about:'À propos', contact:'Contact', lookup:'🔍 Rechercher', tagline:'🔧 Outil gratuit', hero1:"DÉCODEZ N'IMPORTE QUEL", hero2:'CODE DE DÉFAUT', heroSub:'Recherche instantanée de codes OBD2 avec causes, symptômes et guides de réparation.', searchPlaceholder:'Tapez un code: P0300, P0420, ou décrivez un symptôme…', browseCategory:'Parcourir par', category:'Catégorie', viewAll:'Voir toutes les catégories →', allCodesPlus:'+2 600', results:'Résultats pour', codes:'codes', code:'code', noResults:'Aucun code trouvé.', viewDetails:'Voir les détails →', severity:'Toute gravité', critical:'🔴 Critique', moderate:'🟡 Modéré', minor:'🟢 Mineur', disclaimer:'Les données sont à titre indicatif uniquement.', footerDesc:'La base de données OBD2 la plus complète au monde — gratuite et multilingue.', quickLinks:'Liens rapides', popularCodes:'Codes populaires' },
  de: { categories:'Kategorien', allCodes:'Alle Codes', about:'Über uns', contact:'Kontakt', lookup:'🔍 Suchen', tagline:'🔧 Kostenloses Tool', hero1:'FEHLERCODE', hero2:'ENTSCHLÜSSELN', heroSub:'Sofortige OBD2-Fehlercodesuche mit Ursachen, Symptomen und Reparaturanleitungen.', searchPlaceholder:'Code eingeben: P0300, P0420, oder Symptom beschreiben…', browseCategory:'Durchsuchen nach', category:'Kategorie', viewAll:'Alle Kategorien anzeigen →', allCodesPlus:'+2.600', results:'Ergebnisse für', codes:'Codes', code:'Code', noResults:'Keine Codes gefunden.', viewDetails:'Details anzeigen →', severity:'Alle Schweregrade', critical:'🔴 Kritisch', moderate:'🟡 Mäßig', minor:'🟢 Gering', disclaimer:'Daten dienen nur als Referenz.', footerDesc:'Die umfassendste OBD2-Fehlerdatenbank — kostenlos und mehrsprachig.', quickLinks:'Schnelllinks', popularCodes:'Beliebte Codes' },
  pt: { categories:'Categorias', allCodes:'Todos os códigos', about:'Sobre', contact:'Contato', lookup:'🔍 Pesquisar', tagline:'🔧 Ferramenta gratuita', hero1:'DECODIFIQUE QUALQUER', hero2:'CÓDIGO DE FALHA', heroSub:'Pesquisa instantânea de códigos OBD2 com causas, sintomas e guias de reparo.', searchPlaceholder:'Digite um código: P0300, P0420, ou descreva um sintoma…', browseCategory:'Procurar por', category:'Categoria', viewAll:'Ver todas as categorias →', allCodesPlus:'+2.600', results:'Resultados para', codes:'códigos', code:'código', noResults:'Nenhum código encontrado.', viewDetails:'Ver detalhes →', severity:'Toda gravidade', critical:'🔴 Crítico', moderate:'🟡 Moderado', minor:'🟢 Menor', disclaimer:'Os dados são apenas para referência.', footerDesc:'O banco de dados OBD2 mais completo do mundo — gratuito e multilíngue.', quickLinks:'Links rápidos', popularCodes:'Códigos populares' },
  hi: { categories:'श्रेणियां', allCodes:'सभी कोड', about:'हमारे बारे में', contact:'संपर्क', lookup:'🔍 खोजें', tagline:'🔧 निःशुल्क टूल', hero1:'किसी भी', hero2:'फॉल्ट कोड को डीकोड करें', heroSub:'AI-संचालित कारणों, लक्षणों और मरम्मत गाइड के साथ OBD2 कोड खोज।', searchPlaceholder:'कोड टाइप करें: P0300, P0420, या लक्षण बताएं…', browseCategory:'श्रेणी के अनुसार', category:'श्रेणी', viewAll:'सभी श्रेणियां देखें →', allCodesPlus:'2,600+', results:'परिणाम', codes:'कोड', code:'कोड', noResults:'कोई कोड नहीं मिला।', viewDetails:'विवरण देखें →', severity:'सभी गंभीरता', critical:'🔴 गंभीर', moderate:'🟡 मध्यम', minor:'🟢 मामूली', disclaimer:'डेटा केवल संदर्भ के लिए है।', footerDesc:'दुनिया का सबसे व्यापक OBD2 कोड डेटाबेस — मुफ्त और बहुभाषी।', quickLinks:'त्वरित लिंक', popularCodes:'लोकप्रिय कोड' },
}

export function t(lang: LangCode, key: string): string {
  return T[lang]?.[key] ?? T['en'][key] ?? key
}

export function isRTL(lang: LangCode): boolean {
  return LANGUAGES.find(l => l.code === lang)?.rtl ?? false
}
